apiVersion: apps/v1
kind: Deployment
metadata:
  name: callee-service-d
  
spec:
  selector:
    matchLabels:
      app: callee-service
  replicas: 3
  template:
    metadata:
      labels:
        app: callee-service
    spec:
      containers:
        - name: callee-service
          image: himanshubhusan88/callee-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
---

apiVersion: v1
kind: Service
metadata:
  name: callee-service-svc
spec:
  selector:
    app: callee-service
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080 
  type: ClusterIP