apiVersion: v1

kind: Service # Kubernetes resource type (Deployment/Service etc.)

metadata:
  name: springboot-k8s-service # Name of the service
  
spec:
  selector:
    app: springboot-k8s-demo # Should be same as Label mentioned in 'deployment' yaml
      
  ports:
    - protocol: "TCP"
      port: 8080 # Port on which the service is running in the cluster
      targetPort: 8080 # Port exposed by the service
      
  type: NodePort # Type of the service. 'NodePort' means we can access the service by using the node IP and port
  
 