apiVersion: apps/v1
kind: Deployment
metadata:
  name: callee-deploy-stable
  
spec:
  selector:
    matchLabels:
      app: callee-app
      version: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: callee-app
        version: stable
    spec:
      containers:
        - name: callee-service
          image: himanshubhusan88/callee-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080