apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-service-d
  
spec:
  selector:
    matchLabels:
      app: caller-service
  replicas: 1
  template:
    metadata:
      labels:
        app: caller-service
    spec:
      containers:
        - name: caller-service
          image: himanshubhusan88/caller-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
---

apiVersion: v1
kind: Service
metadata:
  name: caller-service-svc
spec:
  selector:
    app: caller-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001 
  type: NodePort